### ISSUE TITLE
prefetch option only available for mapper, not for agent

### ISSUE THREAD

**Issue by kingcu** [ezmobius/nanite#11]
The prefetch option that is a savior when you have high volumes of intense tasks is only available on mappers.  The mapper doesn't really benefit from having a prefetch limit, as the mapper receives mostly pings and registrations, which can be processed really fast.  It is the agent that is going to predominantly be affected, and should also have the option.

I went ahead and forked nanite, made the changes and am using it in production.  This finally fixed my issue with overloading my agents to the point they were unresponsive and had to be killed.  The fork is available on my github page if you are interested in bringing the change upstream.

In the fork, I simply added a configuration option for the agent, including adding the command line options for the nanite-agent script.  I also documented the new config option in the init method, so aside from some review, it should be ready to go.

**Comment by roidrage** [comment]
Cool, I'll merge it later today.

Any reason why you're checking if the prefetch method is there on the AMQP connection?

**Comment by kingcu** [comment]
that was actually brought over from the mapper.rb method.  I left it as I am assuming some versions of the AMQP gem don't have that method?

**Comment by roidrage** [comment]
Ah, gotcha, no worries, I'll look into it.

**Comment by roidrage** [comment]
Merged, thanks!
