### ISSUE TITLE
Nanite and multiples machines

### ISSUE THREAD

**Issue by juanjo** [ezmobius/nanite#19]
Hi,

First: I'm a noob using Nanite.. I'm sorry

I want to use Nanite in a distributed environment with multiple machines and I don't know how can I achieve it. I can't find any examples in google about it. Imagine, for example, that we are using Amazon EC2, but in reality I'll use physical servers

Could you could give me some guidelines, please?
Where I can get information?

Thanks in advance!

**Comment by roidrage** [comment]
It's pretty simple to achieve really. Nanite doesn't care whether an agent connects from a local or a remote machine. You can easily have hundreds of agents spread across several physical or virtual machines. You just need to make sure they have access to RabbitMQ, that's what's important. I'd also suggest using encryption to ensure that communication is secured, especially when machines are on physically different networks.

**Comment by juanjo** [comment]
Thanks mattmatt, again!
I've installed nanite in other machines, and all workers are running perfectly.
