### ISSUE TITLE
RabbitMQ 1.8 support

### ISSUE THREAD

**Issue by bernd** [ezmobius/nanite#22]
I patched nanite to make it work with RabbitMQ 1.8.
The 1.8 version doesn't allow the declaration of an exchange with different parameters anymore.

See "Exchange equivalence" at:
http://lists.rabbitmq.com/pipermail/rabbitmq-announce/2010-June/000025.html

Please review my commit at:
bernd/nanite@747359b0bcda55443e4e62cfba34f0ebdda5a23b

I'm not sure if my changes will do something bad when running with an older RabbitMQ version. Especially the change in `lib/nanite/mapper.rb`. At least the simpleagent example runs again and doesn't throw stuff like the following anymore.

```
NOT_ALLOWED - cannot redeclare exchange 'registration' in vhost '/nanite' with different
type, durable or autodelete value in AMQP::Protocol::Exchange::Declare
```

Thanks,
Bernd

**Comment by roidrage** [comment]
Thanks for the patches. I'll look into them, testing them with a 1.7.1 infrastructure later this week before fully applying them.

**Comment by bernd** [comment]
Just ran the simpleagent example with rabbitmq 2.0.0. Works fine as well.

**Comment by roidrage** [comment]
Merged them into master, changes already included in the mapper_rework branch. Thanks!
