### ISSUE TITLE
rake gem fails with "no such file to load -- spec/rake/spectask"

### ISSUE THREAD

**Issue by ghost** [ezmobius/nanite#24]
I got the following error when trying to install nanite with rspec 2.0.0

mrt@drone02:~/nanite$ rake gem
(in /media/production/users/mrt/nanite)
rake aborted!
no such file to load -- spec/rake/spectask
/media/production/users/mrt/nanite/Rakefile:3
(See full trace by running task with --trace)

Apparently rspec 2.0.0 does not package spec/rake/spectask.

The solution for me was to uninstall rspec 2.0.0 and install rspec 1.1.12 and also json. e.g.

gem uninstall rspec
gem install rspec --version '1.1.12'
gem install json

**Comment by roidrage** [comment]
Nanite is not yet tested with RSpec 2.0.0. It's not high on my list, but I'll upgrade eventually.

**Comment by ghost** [comment]
That's cool. It kinda caught me off guard though, and I don't remember
seeing anything in the docs about it. I thought you might want to know
so you can make a note in the README to help out the next guy.

If you want I'll update the README and send you a push request.
