### ISSUE TITLE
[BUG] Bus Error with ruby 1.9

### ISSUE THREAD

**Issue by ippy04** [ezmobius/nanite#4]
Getting a weird SSL error with ruby 1.9r129 on osx - any help / ideas would be appreciated!

<pre>
$ rake spec
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:31: [BUG] Bus Error
ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-darwin9.7.0]

-- control frame ----------
c:0029 p:---- s:0080 b:0080 l:000079 d:000079 CFUNC  :initialize
c:0028 p:---- s:0078 b:0078 l:000077 d:000077 CFUNC  :new
c:0027 p:0063 s:0075 b:0075 l:000074 d:000074 CLASS  /usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:31
c:0026 p:0011 s:0073 b:0073 l:000072 d:000072 CLASS  /usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:23
c:0025 p:0011 s:0071 b:0071 l:000070 d:000070 CLASS  /usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:22
c:0024 p:0045 s:0069 b:0069 l:000068 d:000068 TOP    /usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:21
c:0023 p:---- s:0067 b:0067 l:000066 d:000066 FINISH
c:0022 p:---- s:0065 b:0065 l:000064 d:000064 CFUNC  :require
c:0021 p:0059 s:0061 b:0061 l:000060 d:000060 TOP    /usr/local/lib/ruby19/site_ruby/1.9.1/openssl.rb:22
c:0020 p:---- s:0059 b:0059 l:000058 d:000058 FINISH
c:0019 p:---- s:0057 b:0057 l:000056 d:000056 CFUNC  :require
c:0018 p:0083 s:0053 b:0053 l:000052 d:000052 TOP    /Users/ippy04/Code/Samples/nanite/lib/nanite.rb:7
c:0017 p:---- s:0051 b:0051 l:000050 d:000050 FINISH
c:0016 p:---- s:0049 b:0049 l:000048 d:000048 CFUNC  :require
c:0015 p:0084 s:0045 b:0045 l:000044 d:000044 TOP    /Users/ippy04/Code/Samples/nanite/spec/spec_helper.rb:6
c:0014 p:---- s:0043 b:0043 l:000042 d:000042 FINISH
c:0013 p:---- s:0041 b:0041 l:000040 d:000040 CFUNC  :require
c:0012 p:0039 s:0037 b:0037 l:000036 d:000036 TOP    /Users/ippy04/Code/Samples/nanite/spec/actor_registry_spec.rb:1
c:0011 p:---- s:0035 b:0035 l:000034 d:000034 FINISH
c:0010 p:---- s:0033 b:0033 l:000032 d:000032 CFUNC  :load
c:0009 p:0012 s:0029 b:0029 l:000020 d:000028 BLOCK  /usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/example_group_runner.rb:15
c:0008 p:---- s:0026 b:0026 l:000025 d:000025 FINISH
c:0007 p:---- s:0024 b:0024 l:000023 d:000023 CFUNC  :each
c:0006 p:0036 s:0021 b:0021 l:000020 d:000020 METHOD /usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/example_group_runner.rb:14
c:0005 p:0097 s:0017 b:0017 l:000016 d:000016 METHOD /usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/options.rb:107
c:0004 p:0068 s:0012 b:0012 l:000011 d:000011 METHOD /usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/command_line.rb:9
c:0003 p:0077 s:0007 b:0006 l:002614 d:002494 EVAL   /usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/bin/spec:4
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:002614 d:002614 TOP    <main>:43044
---------------------------
-- Ruby level backtrace information-----------------------------------------
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:31:in `initialize'
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:31:in `new'
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:31:in `<class:SSLContext>'
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:23:in `<module:SSL>'
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:22:in `<module:OpenSSL>'
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl/ssl.rb:21:in `<top (required)>'
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl.rb:22:in `require'
/usr/local/lib/ruby19/site_ruby/1.9.1/openssl.rb:22:in `<top (required)>'
/Users/ippy04/Code/Samples/nanite/lib/nanite.rb:7:in `require'
/Users/ippy04/Code/Samples/nanite/lib/nanite.rb:7:in `<top (required)>'
/Users/ippy04/Code/Samples/nanite/spec/spec_helper.rb:6:in `require'
/Users/ippy04/Code/Samples/nanite/spec/spec_helper.rb:6:in `<top (required)>'
/Users/ippy04/Code/Samples/nanite/spec/actor_registry_spec.rb:1:in `require'
/Users/ippy04/Code/Samples/nanite/spec/actor_registry_spec.rb:1:in `<top (required)>'
/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/example_group_runner.rb:15:in `load'
/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/example_group_runner.rb:15:in `block in load_files'
/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/example_group_runner.rb:14:in `each'
/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/example_group_runner.rb:14:in `load_files'
/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/options.rb:107:in `run_examples'
/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib/spec/runner/command_line.rb:9:in `run'
/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/bin/spec:4:in `<main>'

-- C level backtrace information -------------------------------------------
0x117042 0   ruby19                              0x00117042 rb_vm_bugreport + 82
0x2c21c 1   ruby19                              0x0002c21c rb_warning + 444
0x2c27b 2   ruby19                              0x0002c27b rb_bug + 43
0xbd37b 3   ruby19                              0x000bd37b rb_enable_interrupt + 75
0x91e0b2bb 4   libSystem.B.dylib                   0x91e0b2bb _sigtramp + 43
0xffffffff 5   ???                                 0xffffffff 0x0 + 4294967295

[NOTE]
You may encounter a bug of Ruby interpreter. Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

rake aborted!
Command /usr/local/bin/ruby19 -I"/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/lib"  "/usr/local/lib/ruby19/gems/1.9.1/gems/rspec-1.2.7/bin/spec" "spec/actor_registry_spec.rb" "spec/actor_spec.rb" "spec/agent_spec.rb" "spec/cached_certificate_store_proxy_spec.rb" "spec/certificate_cache_spec.rb" "spec/certificate_spec.rb" "spec/cluster_spec.rb" "spec/dispatcher_spec.rb" "spec/distinguished_name_spec.rb" "spec/encrypted_document_spec.rb" "spec/job_spec.rb" "spec/local_state_spec.rb" "spec/log_spec.rb" "spec/mapper_spec.rb" "spec/packet_spec.rb" "spec/rsa_key_pair_spec.rb" "spec/secure_serializer_spec.rb" "spec/serializer_spec.rb" "spec/signature_spec.rb" "spec/static_certificate_store_spec.rb" "spec/util_spec.rb" --format specdoc --colour failed
</pre>

**Comment by pmamediagroup** [comment]
same problem with 1.8.7

**Comment by ippy04** [comment]
had to uninstall openssl from macports to fix this...

**Comment by roidrage** [comment]
Is this still an issue? If not I'd like to close it, since it doesn't seem to be related to Nanite?

**Comment by pmamediagroup** [comment]
no, its an issue with mac

**Comment by roidrage** [comment]
Thanks for the update.

**Comment by ippy04** [comment]
I think this can be closed - it's macport related...
